#!/usr/bin/env bash
# wifi for dwm_bar
msg=""

dwm_wifi() {
    connected=$(nmcli d | grep "wlo1" | awk '{ print $3}')
    wifi_name=$(nmcli d | grep "wlo1" | awk '{ print $NF }')
    
    if [[ $connected = "connected" ]]; then
        msg="🛜 ${wifi_name}"
    else
        msg="🔴 $connected"
    fi
}

dwm_wifi

printf " %s " "${msg}"
