format = """
$os\
$directory\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$character
"""

right_format = """
$pijul_channel\
$docker_context\
$package\
$rlang\
$c\
$cmake\
$lua\
$python\
$dotnet\
$meson\
$sudo\
$cmd_duration\
$jobs\
$time\
$status\
$container\
$battery\
"""
add_newline = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[shell]
fish_indicator = 'fish'
format = 'in [$indicator]($style) '
style = 'bold blue'
disabled = false

[c]
symbol = " "

[directory]
read_only = " 󰌾"
truncation_length = 50
format = ' [$path]($style)[$read_only]($read_only_style) '

[battery]
full_symbol = '  '
charging_symbol = '󰂈 '
discharging_symbol = '💀 '

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'
discharging_symbol = '💦 '

[fossil_branch]
symbol = " "

[git_branch]
format = "[$branch]($style)"
symbol = " "
style = "bright-green"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed) ]($style)"
style = "bright-cyan"
conflicted = " =${count}"
untracked = " ?${count}"
modified = " m${count}"
staged = " +${count}"
renamed = " ->${count}"
deleted = " x${count}"
stashed = "≡"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nodejs]
symbol = " "

[os]
format = " [$symbol]($style) "
style = "red"
disabled = true

[os.symbols]
Arch = ""
Artix = ""
Ubuntu = ""
Debian = ""
Fedora = ""
Linux = ""
Windows = "󰍲"


[python]
symbol = " "

[dotnet]
symbol = " "

[rlang]
symbol = "󰟔 "

[rust]
symbol = " "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[ $symbol ]($style)"

[cmd_duration]
format = "[ took $duration ]($style)"
style = "red"
